import express from 'express';
import http from 'http';
import path from 'path';
import { fileURLToPath } from 'url';
import { Server } from 'socket.io';
import { TikTokLiveConnection, WebcastEvent, ControlEvent } from 'tiktok-live-connector';
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),publicDir=path.join(__dirname,'public');
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.json());app.use(express.static(publicDir));
app.get('/live',(_q,r)=>r.sendFile(path.join(publicDir,'index.html')));app.get('/admin',(_q,r)=>r.sendFile(path.join(publicDir,'admin.html')));app.get('/health',(_q,r)=>r.status(200).json({ok:true,service:'live-rank-tiktok'}));
const PORT=process.env.PORT||8091;
let state={connected:false,username:'',paused:false,taps:{},gifts:{},lastChampion:null,lastGift:null,startedAt:Date.now(),timer:{durationSec:180,remainingSec:180,running:false,endsAt:null},video:{enabled:false,url:'',muted:true}};
let connection=null,lastTimerSecond=state.timer.remainingSec;
const cleanUser=(data={})=>{const u=data.user||{};return{id:String(u.userId||u.uniqueId||u.nickname||'anon'),username:u.uniqueId?'@'+String(u.uniqueId).replace(/^@/,''):'@usuario',nickname:u.nickname||u.uniqueId||'Usuário',avatar:u.profilePictureUrl||u.avatarThumb?.urlList?.[0]||u.avatarMedium?.urlList?.[0]||''}};
function giftCoins(data){const d=data.giftDetails||{},e=data.extendedGiftInfo||{};return(Number(d.diamondCount??d.price??e.diamondCount??e.price??data.diamondCount??1)||1)*(Number(data.repeatCount||1)||1)}
function rankings(){const tapRank=Object.values(state.taps).sort((a,b)=>b.taps-a.taps).slice(0,10),giftRank=Object.values(state.gifts).sort((a,b)=>b.coins-a.coins).slice(0,10);return{tapRank,giftRank,top3:giftRank.slice(0,3)}}
function timerSnapshot(){if(state.timer.running&&state.timer.endsAt){state.timer.remainingSec=Math.max(0,Math.ceil((state.timer.endsAt-Date.now())/1000));if(state.timer.remainingSec<=0){state.timer.remainingSec=0;state.timer.running=false;state.timer.endsAt=null}}return{...state.timer}}
function emitState(){timerSnapshot();io.emit('state',{...state,timer:{...state.timer},video:{...state.video},...rankings()})}
setInterval(()=>{const t=timerSnapshot();if(t.remainingSec!==lastTimerSecond){lastTimerSecond=t.remainingSec;emitState();if(t.remainingSec===0)io.emit('timer-finished')}},250);
function setTimer(seconds){const v=Math.max(1,Math.min(86400,Math.floor(Number(seconds)||180)));state.timer={durationSec:v,remainingSec:v,running:false,endsAt:null};lastTimerSecond=v;emitState()}
function startTimer(seconds){if(Number(seconds)>0)setTimer(seconds);if(state.timer.remainingSec<=0)state.timer.remainingSec=state.timer.durationSec;state.timer.running=true;state.timer.endsAt=Date.now()+state.timer.remainingSec*1000;emitState()}
function pauseTimer(){timerSnapshot();state.timer.running=false;state.timer.endsAt=null;emitState()}
function resetTimer(){state.timer.remainingSec=state.timer.durationSec;state.timer.running=false;state.timer.endsAt=null;lastTimerSecond=state.timer.remainingSec;emitState()}
function addTap(user,count){if(state.paused)return;const old=state.taps[user.id]||{...user,taps:0};old.taps+=Math.max(0,Number(count||0));state.taps[user.id]=old;emitState()}
function addGift(user,gift){if(state.paused)return;const old=state.gifts[user.id]||{...user,coins:0,giftCount:0};old.coins+=gift.coins;old.giftCount+=gift.repeatCount||1;old.lastGiftName=gift.name;old.lastGiftImage=gift.image||'';state.gifts[user.id]=old;state.lastGift={...user,...gift,at:Date.now()};const leader=rankings().giftRank[0];if(leader)state.lastChampion={...leader,at:Date.now()};io.emit('gift-event',state.lastGift);emitState()}
async function disconnectTikTok(){try{connection?.disconnect()}catch{}connection=null;state.connected=false;emitState()}
async function connectTikTok(username){await disconnectTikTok();const clean=String(username||'').trim().replace(/^@/,'');if(!clean)throw new Error('Informe o usuário do TikTok.');state.username='@'+clean;connection=new TikTokLiveConnection(clean,{enableExtendedGiftInfo:true});connection.on(ControlEvent.CONNECTED,()=>{state.connected=true;emitState()});connection.on(ControlEvent.DISCONNECTED,()=>{state.connected=false;emitState()});connection.on(ControlEvent.ERROR,e=>io.emit('connector-error',String(e?.message||e)));connection.on(WebcastEvent.LIKE,d=>addTap(cleanUser(d),d.likeCount||0));connection.on(WebcastEvent.GIFT,d=>{if(d.giftDetails?.giftType===1&&!d.repeatEnd)return;addGift(cleanUser(d),{giftId:d.giftId,name:d.giftDetails?.giftName||d.extendedGiftInfo?.name||`Presente ${d.giftId||''}`,repeatCount:Number(d.repeatCount||1),coins:giftCoins(d),image:d.extendedGiftInfo?.image?.urlList?.[0]||d.giftDetails?.giftImage?.urlList?.[0]||''})});const result=await connection.connect();state.connected=true;emitState();return result}
io.on('connection',socket=>{timerSnapshot();socket.emit('state',{...state,timer:{...state.timer},video:{...state.video},...rankings()});socket.on('connect-tiktok',async username=>{try{const r=await connectTikTok(username);socket.emit('connect-result',{ok:true,roomId:r?.roomId})}catch(e){state.connected=false;emitState();socket.emit('connect-result',{ok:false,error:String(e?.message||e)})}});socket.on('disconnect-tiktok',disconnectTikTok);socket.on('pause',v=>{state.paused=!!v;emitState()});socket.on('reset-taps',()=>{state.taps={};emitState()});socket.on('reset-gifts',()=>{state.gifts={};state.lastChampion=null;state.lastGift=null;emitState()});socket.on('reset-all',()=>{state.taps={};state.gifts={};state.lastChampion=null;state.lastGift=null;state.startedAt=Date.now();emitState()});socket.on('timer-set',setTimer);socket.on('timer-start',startTimer);socket.on('timer-pause',pauseTimer);socket.on('timer-reset',resetTimer);socket.on('video-set',p=>{state.video.url=String(p?.url||'').trim();state.video.enabled=!!p?.enabled&&!!state.video.url;state.video.muted=p?.muted!==false;emitState()});socket.on('video-toggle',enabled=>{state.video.enabled=!!enabled&&!!state.video.url;emitState()});socket.on('test-tap',p=>addTap({id:p?.username||'testeTap',username:'@'+String(p?.username||'teste_tap').replace(/^@/,''),nickname:p?.username||'Teste TAP',avatar:''},Number(p?.count||100)));socket.on('test-gift',p=>addGift({id:p?.username||'testeGift',username:'@'+String(p?.username||'teste_presente').replace(/^@/,''),nickname:p?.username||'Teste Presente',avatar:''},{giftId:'TESTE',name:p?.giftName||'Leão',repeatCount:1,coins:Number(p?.coins||1000),image:''}))});
server.listen(PORT,'0.0.0.0',()=>console.log(`LIVE RANK rodando na porta ${PORT}`));